Initial Setup
Racisometro/data pull request #1
Opened 2021-09-03 13:23 UTC by gustwer

Este PR entrega o setup inicial do projeto. Contém a lista de dependências a serem gerenciadas com Pipenv, as variáveis de ambiente, o script principal, etc.

2021-09-08 18:15 UTC, dfernandoso requested changes

2021-09-08 18:15 UTC, dfernandoso commented on README.md
> +[![CircleCI](https://circleci.com/gh/twlabs/Racisometro-Data.svg?style=svg&circle-token=b4a5b5817ae61ea9a3e7b550ecd98bb9ac873cfb)](https://circleci.com/gh/twlabs/Racisometro-Data)
A gente tem acesso a este link do circleCI?
https://circleci.com/gh/twlabs/Racisometro-Data

2021-09-08 18:15 UTC, dfernandoso commented on extract.py
> +        documents.append(tweet_json)
Esta parte aqui é testavel? Podemos testar isso de alguma forma?

2021-09-08 18:15 UTC, dfernandoso commented on data/data_lake.py
> +        return self.__data_lake_output_collection.find()
Esta parte podemos fazer um teste? Tipo: Se encontrar, o que eu espero? Está retornando as informações que fazem sentido para o negócio?

2021-09-09 16:32 UTC, gustwer commented on README.md
> +[![CircleCI](https://circleci.com/gh/twlabs/Racisometro-Data.svg?style=svg&circle-token=b4a5b5817ae61ea9a3e7b550ecd98bb9ac873cfb)](https://circleci.com/gh/twlabs/Racisometro-Data)
Esse arquivo é deprecado, vou remover.

2021-09-09 16:33 UTC, gustwer commented on extract.py
> +        documents.append(tweet_json)
Boa! Sim, vou separar essa lógica e testa-lá.

2021-09-09 16:35 UTC, gustwer commented on data/data_lake.py
> +        return self.__data_lake_output_collection.find()
Acredito que é possível testar somente com uma coleção de testes no MongoDB.

2021-09-10 16:35 UTC, dfernandoso commented on README.md
> +[![CircleCI](https://circleci.com/gh/twlabs/Racisometro-Data.svg?style=svg&circle-token=b4a5b5817ae61ea9a3e7b550ecd98bb9ac873cfb)](https://circleci.com/gh/twlabs/Racisometro-Data)
Ah belezaaa.

2021-09-16 13:44 UTC, merged